version: '3'
services:
  db:
    image: postgres:15.3
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=exampledb
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080


volumes:
  data:
    external: true