"""add imagefield attribute

Revision ID: 1dbe5cead24a
Revises: c79e6c35b35a
Create Date: 2023-12-07 09:40:39.395634

"""
from typing import Sequence, Union
import sqlalchemy_file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbe5cead24a'
down_revision: Union[str, None] = 'c79e6c35b35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('ins_fea_img', sqlalchemy_file.types.ImageField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'ins_fea_img')
    # ### end Alembic commands ###
