"""init

Revision ID: 4419b0087177
Revises: 
Create Date: 2023-12-06 19:55:10.625121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4419b0087177'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('ins_fea_id', sa.Integer(), nullable=False),
    sa.Column('ins_fea_name', sa.String(), nullable=False),
    sa.Column('ins_fea_desc', sa.String(), nullable=True),
    sa.Column('ins_fea_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ins_fea_id')
    )
    op.drop_table('inst_features')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inst_features',
    sa.Column('ins_fea_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ins_fea_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ins_fea_desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ins_fea_img', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ins_fea_id', name='inst_features_pkey')
    )
    op.drop_table('facilities')
    # ### end Alembic commands ###
