"""delete img attribute

Revision ID: 9acc8a51798d
Revises: 4419b0087177
Create Date: 2023-12-06 20:06:06.966264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acc8a51798d'
down_revision: Union[str, None] = '4419b0087177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'ins_fea_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('ins_fea_img', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
